
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-environments-new1
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/sisi9422/gitops-demo.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/sisi9422/gitops-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true